import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import Card from "../../components/ui/Card";
import Input from "../../components/ui/Input";
import Button from "../../components/ui/Button";
import { useAuth } from "../../context/AuthContext";

export default function StudentLoginPage() {
  const { loginStudent } = useAuth();
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [rollNo, setRollNo] = useState("");
  const [studentId, setStudentId] = useState("");
  const [submitting, setSubmitting] = useState(false);

  async function onSubmit(e) {
    e.preventDefault();
    setSubmitting(true);
    try {
      await loginStudent({ name, rollNo, studentId });
      toast.success("Welcome!");
      navigate("/student", { replace: true });
    } catch (err) {
      toast.error(err?.response?.data?.message || err.message || "Login failed");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="min-h-full">
      <div className="mx-auto max-w-md px-4 py-10">

        {/* ── Demo Info Banner ── */}
        <div className="mt-10 mb-4 rounded-2xl border border-blue-200 bg-blue-50 px-5 py-4">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-blue-500 text-lg">ℹ️</span>
            <span className="text-sm font-semibold text-blue-800">Demo Access — Student</span>
          </div>
          <p className="text-xs text-blue-700 leading-relaxed">
            Student credentials are issued by the warden. To explore student features,
            first{" "}
            <Link to="/warden/login" className="font-semibold underline">
              log in as Warden
            </Link>{" "}
            → go to <strong>Manage Students</strong> → register a student and copy the generated
            Student ID, then come back here to log in.
          </p>
        </div>

        {/* ── Login Form ── */}
        <Card className="p-8">
          <div className="text-2xl font-bold tracking-tight text-gray-900">Student Login</div>
          <div className="mt-2 text-sm text-gray-600">
            Login using your name, roll number, and the unique ID provided by the warden.
          </div>
          <form className="mt-5 space-y-4" onSubmit={onSubmit}>
            <Input
              label="Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <Input label="Roll No" value={rollNo} onChange={(e) => setRollNo(e.target.value)} />
            <Input
              label="Unique Student ID"
              value={studentId}
              onChange={(e) => setStudentId(e.target.value)}
              placeholder="e.g. SOS-21CS101-19-7F3A1C"
            />
            <Button type="submit" disabled={submitting} className="w-full">
              {submitting ? "Signing in..." : "Login"}
            </Button>
          </form>
          <div className="mt-6 text-xs text-gray-400 text-center">
            Student IDs are generated by the warden — no self-registration available.
          </div>
        </Card>
      </div>
    </div>
  );
}


